name: ip_geolocation_api
description: A dart package to flutter or dart projects to get your geolocation data from your IP
version: 0.0.2
author: zpw
homepage: https://github.com/darwin-morocho/dart-ip-geolocation-api


environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  http: ^0.13.4
  meta: ^1.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
